/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create an account and return a freshly-issued bearer token.
         *
         *     Sets the ``workshop_access_token`` httpOnly cookie on the
         *     response so the browser session is established without any
         *     JS-side token handling.
         *
         *     Args:
         *         request: Inbound request (used for the rate-limit key).
         *         response: Active response, mutated to carry the session cookie.
         *         payload: Validated signup body (full name, email, password).
         *         session: Active async database session.
         *
         *     Returns:
         *         A bearer token and the public view of the new account.
         *
         *     Raises:
         *         RateLimitedError: 429 if the ``(IP, email)`` key has
         *             exceeded its attempt budget.
         *         EmailAlreadyExistsError: 409 if the email is already
         *             registered.
         */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Sign in with email and password.
         *
         *     Sets the ``workshop_access_token`` httpOnly cookie on the
         *     response.
         *
         *     Args:
         *         request: Inbound request (used for the rate-limit key).
         *         response: Active response, mutated to carry the session cookie.
         *         payload: Validated login body (email, password).
         *         session: Active async database session.
         *
         *     Returns:
         *         A bearer token and the public view of the account.
         *
         *     Raises:
         *         RateLimitedError: 429 if the ``(IP, email)`` key has
         *             exceeded its attempt budget.
         *         InvalidCredentialsError: 401 if the email is unknown or
         *             the password does not match. The error message is
         *             intentionally the same in both cases to avoid
         *             leaking which emails are registered.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently signed-in account.
         *
         *     Useful for the frontend to refresh its cached user view after
         *     a page reload. The session is now httpOnly-only on the browser
         *     side, so this endpoint is the only way to rehydrate the
         *     in-memory user view after the cookie has been written.
         *
         *     Args:
         *         user: The signed-in account, resolved by the auth dependency.
         *
         *     Returns:
         *         The public view of the account.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie. Idempotent - safe to call when signed out.
         *
         *     The bearer token is stateless, so logout only clears the
         *     cookie; clients storing the token in ``localStorage`` must
         *     discard it themselves. The handler mutates the
         *     FastAPI-injected ``response`` and returns the same instance
         *     so the cookie header is preserved on the wire.
         *
         *     Args:
         *         response: Active response, mutated to clear the cookie.
         *
         *     Returns:
         *         The same response with a 204 status.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness probe used by ``docker-compose.yml`` and orchestrators.
         *
         *     Returns:
         *         A constant ``{"status": "healthy"}`` payload with HTTP 200.
         *         This endpoint intentionally does not check the database -
         *         a slow query would flap the container. Add a separate
         *         ``/readiness`` probe if you need a dependency check.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workshops
         * @description List workshops with search, filter, and pagination.
         *
         *     The catalogue only ever contains ``published`` sessions for
         *     the public. The configured administrator sees every
         *     lifecycle state - draft and cancelled sessions included -
         *     so the admin management surface can oversee the full
         *     lifecycle.
         *
         *     Args:
         *         q: Optional case-insensitive substring matched against
         *             the title and description.
         *         category: Optional exact category filter.
         *         state: ``upcoming`` (default) hides sessions that have
         *             started; ``past`` shows only those; ``all`` shows
         *             both.
         *         limit: Page size (1..100).
         *         offset: Number of matching rows to skip.
         *         following: When ``true``, restrict results to workshops
         *             from organizations the caller follows (roadmap 2.3).
         *             Requires a signed-in account - an anonymous request
         *             with ``following=true`` is a 401 rather than an
         *             empty page, so the caller learns the filter needs
         *             authentication instead of silently seeing nothing.
         *         session: Active async database session.
         *         user: The signed-in account, when any.
         *
         *     Returns:
         *         A ``WorkshopListResponse`` envelope ordered by
         *         ``starts_at`` ascending.
         *
         *     Raises:
         *         HTTPException: 401 when ``following=true`` and the
         *             caller is anonymous.
         */
        get: operations["list_workshops_api_workshops_get"];
        put?: never;
        /**
         * Create Workshop
         * @description Create a workshop session as an administrator or organization member.
         *
         *     When the payload names an ``organization_id``, the caller
         *     must be a member of that organization (or the configured
         *     administrator); the check happens in the service layer.
         */
        post: operations["create_workshop_api_workshops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Stream reservation events over Server-Sent Events.
         *
         *     The browser opens a single ``EventSource`` against this URL and
         *     branches on each event's ``workshop_id`` to update the right
         *     card on the list view (and the open detail view, if any).
         *
         *     A heartbeat comment (``: keepalive``) is emitted on the
         *     interval configured by ``Settings.sse_heartbeat_seconds`` so
         *     intermediate proxies (nginx, load balancers) do not close the
         *     connection on idle.
         *
         *     Returns:
         *         A ``text/event-stream`` response that streams
         *         ``reservation_created`` and ``reservation_cancelled`` events.
         */
        get: operations["stream_events_api_workshops_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{workshop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workshop
         * @description Fetch a single published workshop and the caller's visible reservations.
         *
         *     Anonymous requests see an empty reservation list. Signed-in
         *     requests see only their own active reservations on this
         *     workshop - this is the privacy boundary enforced by
         *     ``workshop_service.get_workshop_detail``. The signed-in
         *     caller's waitlist position is included when they hold a
         *     place in line.
         *
         *     The configured administrator may also read draft and
         *     cancelled sessions, which is what the admin management
         *     surface needs to edit or re-publish them; every other
         *     caller gets a 404 for non-published workshops.
         *
         *     Args:
         *         workshop_id: Workshop UUID from the URL.
         *         session: Active async database session.
         *         user: The signed-in account if any.
         *
         *     Returns:
         *         The detail payload with computed ``available_spots``,
         *         the caller's reservations, and their ``waitlist_position``.
         *
         *     Raises:
         *         WorkshopNotFoundError: 404 if no published workshop has
         *             this id (non-administrators only; the administrator
         *             may read any state).
         */
        get: operations["get_workshop_api_workshops__workshop_id__get"];
        /**
         * Update Workshop
         * @description Edit a workshop's mutable fields as an administrator or organization member.
         *
         *     When the payload names an ``organization_id``, ownership is
         *     reassigned and the caller must be a member of the new
         *     organization (or the configured administrator).
         */
        put: operations["update_workshop_api_workshops__workshop_id__put"];
        post?: never;
        /**
         * Delete Workshop
         * @description Delete an unbooked workshop session as an administrator or organization member.
         */
        delete: operations["delete_workshop_api_workshops__workshop_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{workshop_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Workshop
         * @description Publish a draft workshop as an administrator or organization member.
         */
        post: operations["publish_workshop_api_workshops__workshop_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{workshop_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Workshop
         * @description Cancel a workshop as an administrator or organization member.
         *
         *     Refused with 409 while active reservations exist.
         */
        post: operations["cancel_workshop_api_workshops__workshop_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{workshop_id}/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Waitlist
         * @description Join a workshop's waitlist.
         *
         *     Requires a signed-in account. Joining is idempotent: a
         *     caller who already holds an active place in line gets that
         *     entry back with ``replayed=true``.
         *
         *     Args:
         *         workshop_id: Workshop UUID from the URL.
         *         session: Active async database session.
         *         user: The signed-in account joining.
         *
         *     Returns:
         *         The waitlist entry and the caller's queue position.
         *
         *     Raises:
         *         WorkshopNotFoundError: 404 if the workshop is missing
         *             or not published.
         *         RegistrationClosedError: 409 if the registration
         *             window has closed.
         *         AlreadyReservedError: 409 if the caller already holds
         *             a seat.
         */
        post: operations["join_waitlist_api_workshops__workshop_id__waitlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{workshop_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Review
         * @description Review a workshop after attending it (roadmap 2.4).
         *
         *     Any signed-in account may call this, but the service
         *     layer accepts the review only when the caller held a
         *     reservation for the workshop (any status - a cancelled
         *     booking still counts as having attended) **and** the
         *     workshop's session has ended (``ends_at``, falling back
         *     to ``starts_at`` when the workshop declares no explicit
         *     end). One review per user per workshop: a second review
         *     is rejected with ``review_already_exists`` before the
         *     insert, with the unique constraint
         *     ``uq_reviews_workshop_user`` as the race-free backstop.
         *
         *     Args:
         *         workshop_id: Workshop UUID from the URL.
         *         payload: Validated review body (rating 1..5,
         *             optional text).
         *         session: Active async database session.
         *         user: The signed-in account writing the review.
         *
         *     Returns:
         *         The created ``ReviewResponse``.
         *
         *     Raises:
         *         WorkshopNotFoundError: 404 if no published workshop
         *             has this id.
         *         ReviewNotEligibleError: 409 if the session has not
         *             ended or the caller never held a reservation.
         *         ReviewAlreadyExistsError: 409 if the caller already
         *             reviewed this workshop.
         */
        post: operations["create_review_api_workshops__workshop_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Reservations
         * @description List the signed-in account's reservations, newest first.
         *
         *     Each row carries the parent workshop's title so the dashboard
         *     can render without a second round-trip per row.
         *
         *     Args:
         *         user: The signed-in account.
         *         session: Active async database session.
         *
         *     Returns:
         *         A list of ``MyReservationResponse`` ordered by
         *         ``created_at`` descending.
         */
        get: operations["my_reservations_api_reservations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Waitlist Entries
         * @description List the signed-in account's active waitlist entries.
         *
         *     Each row carries the parent workshop's title so the
         *     account view can render a human-friendly label without
         *     a second round-trip per row, plus the caller's 1-based
         *     position in that workshop's queue. Only active places
         *     in line are returned; promoted and cancelled entries
         *     are historical.
         *
         *     Args:
         *         user: The signed-in account.
         *         session: Active async database session.
         *
         *     Returns:
         *         A list of ``MyWaitlistEntryResponse`` ordered by
         *         ``created_at`` ascending (oldest place in line
         *         first).
         */
        get: operations["my_waitlist_entries_api_waitlist_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservations/{reservation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reservation
         * @description Fetch a single reservation by id (owner only).
         *
         *     This backs the ticket page (plan 1.4): the signed-in caller
         *     reads their own reservation - including its booking code - to
         *     render the QR ticket. A reservation owned by another account,
         *     or an unknown id, is a 404 so the API does not leak which
         *     reservations exist.
         *
         *     Args:
         *         reservation_id: Reservation UUID from the URL.
         *         session: Active async database session.
         *         user: The signed-in account.
         *
         *     Returns:
         *         The caller's ``ReservationResponse``.
         *
         *     Raises:
         *         ReservationNotFoundError: 404 if the reservation does not
         *             exist or is owned by another account.
         */
        get: operations["get_reservation_api_reservations__reservation_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Reservation
         * @description Cancel a reservation. Idempotent on a second call.
         *
         *     Requires a valid bearer token. The call only succeeds when the
         *     reservation is owned by the signed-in account; otherwise a 404 is
         *     returned to avoid leaking the existence of someone else's booking.
         *     There is no anonymous or "legacy" cancellation path: every
         *     reservation created today is owned, and ownership is the sole
         *     authorization for a cancel.
         *
         *     A second ``DELETE`` on the same id is a no-op and returns 200
         *     with the existing ``cancelled_at``. This makes client retries
         *     safe. Cancelling releases the seat and, when a waitlist exists,
         *     promotes the oldest waitlisted attendee inside the same
         *     transaction.
         *
         *     Args:
         *         reservation_id: Reservation UUID from the URL.
         *         session: Active async database session.
         *         user: The signed-in account (required).
         *
         *     Returns:
         *         The cancelled (or already-cancelled) reservation as a
         *         ``ReservationCancelResponse``.
         *
         *     Raises:
         *         HTTPException: 401 if the bearer token is missing or invalid.
         *         ReservationNotFoundError: 404 if the reservation does not
         *             exist or the caller is not authorized to cancel it.
         */
        delete: operations["cancel_reservation_api_reservations__reservation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workshops/{workshop_id}/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Reservation
         * @description Reserve a seat on a workshop.
         *
         *     Requires a signed-in account and an ``Idempotency-Key`` header. A
         *     retried request with the same key and same workshop returns the
         *     original reservation with HTTP 200; a fresh request returns 201. A
         *     key only ever replays the reservation created by the **same**
         *     account, so reusing somebody else's key cannot disclose their
         *     booking.
         *
         *     The body still carries ``attendee_name`` / ``attendee_email`` for
         *     wire compatibility, but the authenticated account is authoritative:
         *     those values are ignored and the reservation is stored against the
         *     account's own name and email.
         *
         *     The header is validated to be 1..255 characters so we do
         *     not silently accept a missing, empty, or absurdly large key.
         *     The service layer would otherwise treat each oversized value
         *     as a brand-new key and risk polluting the idempotency table
         *     (or running the DB out of space).
         *
         *     Args:
         *         response: FastAPI response object, mutated to 200 on replay.
         *         workshop_id: Workshop UUID from the URL.
         *         payload: Validated reservation body (name, email); ignored
         *             in favour of the authenticated account.
         *         session: Active async database session.
         *         idempotency_key: Client-supplied token; same value on retry
         *             replays the original reservation.
         *         user: The signed-in account that will own the reservation.
         *
         *     Returns:
         *         The created (or replayed) reservation.
         *
         *     Raises:
         *         WorkshopNotFoundError: 404.
         *         RegistrationClosedError: 409 if the workshop has started or
         *             its registration deadline has passed.
         *         WorkshopFullError: 409 if the workshop is at capacity.
         *         AlreadyReservedError: 409 if the attendee already has an
         *             active booking for this workshop.
         */
        post: operations["create_reservation_api_workshops__workshop_id__reservations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist/{waitlist_entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave Waitlist
         * @description Leave a waitlist.
         *
         *     Requires a valid bearer token and ownership of the waitlist
         *     entry. A foreign or unknown id is a 404 so the API does not
         *     leak which waitlist entries exist. Leaving an already-cancelled
         *     or promoted entry is a no-op that returns the row as-is.
         *
         *     Args:
         *         waitlist_entry_id: Waitlist entry UUID from the URL.
         *         session: Active async database session.
         *         user: The signed-in account that owns the entry.
         *
         *     Returns:
         *         The (now cancelled) ``WaitlistEntryResponse``.
         *
         *     Raises:
         *         WaitlistEntryNotFoundError: 404 if the entry does not exist
         *             or is owned by another account.
         */
        delete: operations["leave_waitlist_api_waitlist__waitlist_entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Organization
         * @description Create an organization and make the caller its owner.
         *
         *     The creator receives an ``owner`` membership and is
         *     promoted to the ``organizer`` platform role in the
         *     same transaction, so the new organization is
         *     immediately manageable by its owner.
         *
         *     Args:
         *         payload: Validated creation payload (name and
         *             optional slug).
         *         session: Active async database session.
         *         user: The signed-in account creating the
         *             organization.
         *
         *     Returns:
         *         The new organization together with the creator's
         *         ``owner`` membership.
         */
        post: operations["create_organization_api_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{organization_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow Organization
         * @description Follow an organization (roadmap 2.3).
         *
         *     Requires a signed-in account. Following is
         *     idempotent: a caller who already follows the
         *     organization gets the existing follow back with
         *     HTTP 200 instead of 201, so client retries are
         *     safe. The response carries the organization with
         *     its refreshed ``followers_count``.
         *
         *     Args:
         *         response: Active response, mutated to 200 (from
         *             the default 201) on an idempotent replay.
         *         organization_id: Organization to follow.
         *         session: Active async database session.
         *         user: The signed-in account following.
         *
         *     Returns:
         *         The followed organization with its
         *         ``followers_count``.
         *
         *     Raises:
         *         OrganizationNotFoundError: 404 if no organization
         *             has this id.
         *         CannotFollowOwnOrganizationError: 409 if the
         *             caller is a member of the organization.
         */
        post: operations["follow_organization_api_organizations__organization_id__follow_post"];
        /**
         * Unfollow Organization
         * @description Unfollow an organization (roadmap 2.3).
         *
         *     Requires a signed-in account. Unfollowing is
         *     idempotent: a caller who does not follow the
         *     organization still gets a successful response with
         *     the (unchanged) ``followers_count``, so client
         *     retries are safe.
         *
         *     Args:
         *         organization_id: Organization to unfollow.
         *         session: Active async database session.
         *         user: The signed-in account unfollowing.
         *
         *     Returns:
         *         The organization with its refreshed
         *         ``followers_count``.
         *
         *     Raises:
         *         OrganizationNotFoundError: 404 if no organization
         *             has this id.
         */
        delete: operations["unfollow_organization_api_organizations__organization_id__follow_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizer/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organizer Stats
         * @description Return the calling organizer's dashboard statistics.
         *
         *     Args:
         *         session: Active async database session.
         *         user: The calling organizer, resolved by
         *             ``get_current_organizer``.
         *
         *     Returns:
         *         An ``OrganizerDashboardResponse`` with the
         *         total active bookings across the caller's
         *         workshops, the count of upcoming published
         *         sessions, and the per-workshop breakdown
         *         (booking counts and attendee lists with
         *         booking codes).
         *
         *     Raises:
         *         HTTPException: 401 if the caller is not
         *             signed in; 403 if the caller is a plain
         *             attendee with no organization membership.
         */
        get: operations["get_organizer_stats_api_organizer_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountCreate
         * @description Registration payload for a new personal account.
         *
         *     Attributes:
         *         full_name: Display name (1..200 chars).
         *         email: Valid email; lowercased and trimmed before persistence
         *             so duplicate-account detection is case-insensitive.
         *         password: Plain-text password (8..128 chars). Hashed with
         *             Argon2id before being stored; the plaintext is never
         *             persisted or logged.
         */
        AccountCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * AuthResponse
         * @description Token + account returned after signup or login.
         *
         *     Attributes:
         *         access_token: JWT bearer token. The frontend stores this in
         *             ``localStorage`` and sends it as ``Authorization: Bearer ...``.
         *         token_type: Always ``"bearer"`` (kept explicit for forward
         *             compatibility if refresh tokens are ever introduced).
         *         user: The account the token represents.
         */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Credentials used to sign in on any device.
         *
         *     Attributes:
         *         email: Account email; normalized identically to signup.
         *         password: Plain-text password to verify against the stored hash.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MyReservationResponse
         * @description Reservation enriched with its workshop title.
         *
         *     Used by ``GET /api/reservations/me`` so the signed-in account
         *     dashboard can show a human-friendly label without a second
         *     round-trip per row.
         *
         *     Attributes:
         *         workshop_title: Title of the parent workshop, joined in
         *             ``reservation_queries.list_user_reservations``.
         */
        MyReservationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /** Attendee Name */
            attendee_name: string;
            /** Attendee Email */
            attendee_email: string;
            /**
             * Booking Code
             * @default
             */
            booking_code: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Workshop Title */
            workshop_title: string;
        };
        /**
         * MyWaitlistEntryResponse
         * @description Waitlist entry enriched with its workshop title and queue position.
         *
         *     Used by ``GET /api/waitlist/me`` so the signed-in
         *     account view can show a human-friendly label and the
         *     caller's place in line for each active entry without a
         *     second round-trip per row.
         *
         *     Attributes:
         *         workshop_title: Title of the parent workshop, joined
         *             in ``reservation_queries.list_user_waitlist_entries``.
         *         position: The caller's 1-based position in the
         *             workshop's queue.
         */
        MyWaitlistEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Promoted At */
            promoted_at?: string | null;
            /** Workshop Title */
            workshop_title: string;
            /** Position */
            position: number;
        };
        /**
         * OrganizationCreate
         * @description Validated payload for creating an organization.
         *
         *     Attributes:
         *         name: Human-readable organization name (1..200 chars).
         *         slug: Optional URL-safe identifier. When omitted, one
         *             is derived from ``name``. Uniqueness is enforced
         *             by the database.
         */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /**
         * OrganizationMembershipResponse
         * @description A user's membership in an organization.
         *
         *     The membership is keyed on the ``(user_id, organization_id)``
         *     pair, so the response exposes both ids rather than a single
         *     surrogate ``id``.
         *
         *     Attributes:
         *         user_id: Member account UUID.
         *         organization_id: Organization UUID.
         *         role: ``owner`` or ``member``.
         *         created_at: When the membership was created.
         */
        OrganizationMembershipResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OrganizationResponse
         * @description Organization payload returned by the organizations API.
         *
         *     Attributes:
         *         id: Organization UUID.
         *         name: Human-readable name.
         *         slug: Unique URL-safe identifier.
         *         created_at: Organization creation timestamp.
         *         membership: The requesting user's membership. Populated
         *             on creation (the creator becomes the owner); ``None``
         *             for plain reads that do not resolve a membership.
         *         followers_count: Number of accounts following the
         *             organization (roadmap 2.3). Computed at read time;
         *             a freshly created organization has none.
         */
        OrganizationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            membership?: components["schemas"]["OrganizationMembershipResponse"] | null;
            /**
             * Followers Count
             * @default 0
             */
            followers_count: number;
        };
        /**
         * OrganizerAttendeeSummary
         * @description One reservation on an organizer's workshop.
         *
         *     Attributes:
         *         reservation_id: Reservation UUID.
         *         attendee_name: Attendee's full name.
         *         attendee_email: Attendee's email (already
         *             lowercased).
         *         booking_code: Server-generated confirmation
         *             code (``WKS-`` + 6 chars); the check-in
         *             lookup key.
         *         status: ``"active"`` or ``"cancelled"``.
         *         created_at: Reservation creation timestamp.
         */
        OrganizerAttendeeSummary: {
            /**
             * Reservation Id
             * Format: uuid
             */
            reservation_id: string;
            /** Attendee Name */
            attendee_name: string;
            /** Attendee Email */
            attendee_email: string;
            /**
             * Booking Code
             * @default
             */
            booking_code: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OrganizerDashboardResponse
         * @description Payload returned by ``GET /api/organizer/stats``.
         *
         *     Attributes:
         *         total_bookings: Total active reservations across
         *             the caller's workshops.
         *         upcoming_sessions: Count of the caller's
         *             published workshops that have not started
         *             yet.
         *         workshops: The caller's own workshops ordered by
         *             ``starts_at`` ascending, each with its
         *             booking count and attendee list.
         */
        OrganizerDashboardResponse: {
            /** Total Bookings */
            total_bookings: number;
            /** Upcoming Sessions */
            upcoming_sessions: number;
            /** Workshops */
            workshops?: components["schemas"]["OrganizerWorkshopStats"][];
        };
        /**
         * OrganizerWorkshopStats
         * @description Per-workshop breakdown on the organizer dashboard.
         *
         *     Attributes:
         *         workshop_id: Workshop UUID.
         *         title: Human-readable title.
         *         starts_at: Timezone-aware start timestamp.
         *         ends_at: Timezone-aware end timestamp, or ``None``.
         *         status: Lifecycle state (``draft`` / ``published`` /
         *             ``cancelled``).
         *         booking_count: Number of **active** reservations.
         *         attendees: Every reservation ever made for the
         *             workshop (any status), oldest first, each
         *             with its booking code.
         */
        OrganizerWorkshopStats: {
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Status */
            status: string;
            /** Booking Count */
            booking_count: number;
            /** Attendees */
            attendees?: components["schemas"]["OrganizerAttendeeSummary"][];
        };
        /**
         * ReservationCancelResponse
         * @description Payload returned by ``DELETE /api/reservations/{id}``.
         *
         *     Attributes:
         *         id: Reservation UUID.
         *         status: Always ``"cancelled"`` on success (a second cancel
         *             returns 200 with the existing cancelled row).
         *         cancelled_at: Timestamp at which the reservation was cancelled.
         */
        ReservationCancelResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Cancelled At */
            cancelled_at: string | null;
        };
        /**
         * ReservationCreate
         * @description Request body for ``POST /api/workshops/{id}/reservations``.
         *
         *     Attributes:
         *         attendee_name: Full name of the attendee (1..200 chars).
         *         attendee_email: Valid email (normalized to lowercase, trimmed).
         *             The database partial unique index treats this as the
         *             natural key for "is this person already booked?".
         */
        ReservationCreate: {
            /**
             * Attendee Name
             * @description Full name of the attendee
             */
            attendee_name: string;
            /**
             * Attendee Email
             * Format: email
             * @description Valid email address of the attendee
             */
            attendee_email: string;
        };
        /**
         * ReservationResponse
         * @description Standard reservation payload returned by create / list / cancel.
         *
         *     Attributes:
         *         id: Reservation UUID.
         *         workshop_id: Parent workshop UUID.
         *         attendee_name: Attendee's full name.
         *         attendee_email: Attendee's email (already lowercased).
         *         booking_code: Server-generated confirmation code
         *             (``WKS-`` + 6 chars). This is the check-in lookup
         *             key and the value printed on the ticket.
         *         status: ``"active"`` or ``"cancelled"``.
         *         created_at: Insert timestamp.
         *         cancelled_at: Cancellation timestamp, or ``None`` while active.
         */
        ReservationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /** Attendee Name */
            attendee_name: string;
            /** Attendee Email */
            attendee_email: string;
            /**
             * Booking Code
             * @default
             */
            booking_code: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cancelled At */
            cancelled_at?: string | null;
        };
        /**
         * ReservationSummary
         * @description Compact view of a reservation embedded in workshop details.
         *
         *     Attributes:
         *         id: Reservation UUID.
         *         attendee_name: Attendee's full name.
         *         attendee_email: Attendee's email (already lowercased).
         *         created_at: Reservation creation timestamp.
         */
        ReservationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Attendee Name */
            attendee_name: string;
            /** Attendee Email */
            attendee_email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReviewCreate
         * @description Validated payload for ``POST /api/workshops/{id}/reviews``.
         *
         *     Attributes:
         *         rating: Integer rating in 1..5. Bounds are enforced
         *             here (422) and by the ``ck_reviews_rating``
         *             database CHECK as a backstop.
         *         text: Optional free-form comment (max 4000 chars).
         */
        ReviewCreate: {
            /** Rating */
            rating: number;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * ReviewResponse
         * @description A review as returned to its author by the write endpoint.
         *
         *     Attributes:
         *         id: Review UUID.
         *         workshop_id: Parent workshop UUID.
         *         user_id: Reviewing account UUID.
         *         rating: Integer rating in 1..5.
         *         text: The comment (possibly empty).
         *         created_at: Review creation timestamp.
         */
        ReviewResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Rating */
            rating: number;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserResponse
         * @description Public view of an account.
         *
         *     Deliberately omits ``password_hash`` so this model is safe to
         *     embed in any response.
         *
         *     Attributes:
         *         id: Account UUID.
         *         full_name: Display name.
         *         email: Account email (already lowercased at write time).
         *         created_at: Account creation timestamp.
         *         role: Platform role - ``attendee``, ``organizer``, or
         *             ``admin`` (roadmap 2.1).
         *         is_admin: ``True`` only for the environment-configured
         *             super-admin account.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Role
             * @default attendee
             */
            role: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WaitlistEntryResponse
         * @description A place in line on a workshop's waitlist.
         *
         *     Attributes:
         *         id: Waitlist entry UUID.
         *         workshop_id: Parent workshop UUID.
         *         status: ``active`` / ``promoted`` / ``cancelled``.
         *         created_at: When the caller joined the waitlist.
         *         promoted_at: When the entry was promoted, or ``None``.
         */
        WaitlistEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Promoted At */
            promoted_at?: string | null;
        };
        /**
         * WaitlistJoinResponse
         * @description Response for joining a waitlist.
         *
         *     Attributes:
         *         entry: The waitlist entry (existing on an idempotent
         *             re-join).
         *         position: The caller's 1-based position in the queue.
         *         replayed: ``True`` when an existing active entry was
         *             returned instead of creating a new one.
         */
        WaitlistJoinResponse: {
            entry: components["schemas"]["WaitlistEntryResponse"];
            /** Position */
            position: number;
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
        };
        /**
         * WorkshopCreate
         * @description Validated payload for an administrator-created workshop.
         *
         *     Attributes:
         *         title: Human-readable title.
         *         starts_at: Timezone-aware start timestamp.
         *         ends_at: Optional timezone-aware end timestamp.
         *         max_capacity: Maximum number of active reservations.
         *         description: Long-form session description.
         *         category: Category label used for filtering.
         *         location: Where the session takes place.
         *         registration_closes_at: Optional booking deadline.
         *         organization_id: Optional owning organization. When
         *             set, the caller must be an administrator or a
         *             member of that organization (enforced in
         *             ``workshop_service.create_workshop``).
         */
        WorkshopCreate: {
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Max Capacity */
            max_capacity: number;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Registration Closes At */
            registration_closes_at?: string | null;
            /** Organization Id */
            organization_id?: string | null;
        };
        /**
         * WorkshopDetailResponse
         * @description Detailed workshop payload including its active reservations.
         *
         *     When the request is made by a signed-in user, the embedded
         *     ``reservations`` list contains only that user's own active
         *     bookings (see ``workshop_service.get_workshop_detail``). For
         *     anonymous requests the list is always empty - the brief calls
         *     for a private-by-default model where only your own bookings
         *     are visible.
         *
         *     Attributes:
         *         id: Workshop UUID.
         *         title: Human-readable title.
         *         starts_at: Timezone-aware start timestamp.
         *         ends_at: Timezone-aware end timestamp, or ``None``.
         *         max_capacity: Total seats.
         *         available_spots: Seats not yet reserved.
         *         description: Long-form session description.
         *         category: Category label used for filtering.
         *         location: Where the session takes place.
         *         registration_closes_at: Booking deadline, or ``None``.
         *         status: Lifecycle state.
         *         organization_id: UUID of the owning organization, or
         *             ``None`` for platform-managed workshops.
         *         reservations: Active reservations visible to the caller
         *             (see class docstring).
         *         waitlist_position: The caller's 1-based position in the
         *             waitlist, or ``None`` when they are not waitlisted.
         *         rating_average: Average review rating (1..5), or
         *             ``None`` when the workshop has no reviews yet.
         *         rating_count: Number of reviews written for the
         *             workshop.
         *         reviews: The workshop's reviews, newest first,
         *             each carrying the reviewer's display name.
         *         created_at: Workshop creation timestamp.
         */
        WorkshopDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Max Capacity */
            max_capacity: number;
            /** Available Spots */
            available_spots: number;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Registration Closes At */
            registration_closes_at?: string | null;
            /**
             * Status
             * @default published
             */
            status: string;
            /** Organization Id */
            organization_id?: string | null;
            /** Reservations */
            reservations: components["schemas"]["ReservationSummary"][];
            /** Waitlist Position */
            waitlist_position?: number | null;
            /** Rating Average */
            rating_average?: number | null;
            /**
             * Rating Count
             * @default 0
             */
            rating_count: number;
            /** Reviews */
            reviews?: components["schemas"]["WorkshopReviewResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WorkshopListResponse
         * @description Paginated workshop list envelope (plan 1.3).
         *
         *     ``GET /api/workshops`` returns this envelope rather than a
         *     bare array so clients can render "load more" and know when
         *     the catalogue is exhausted. This is a breaking shape change
         *     from the previous bare-array response; the frontend is
         *     updated in the same release.
         *
         *     Attributes:
         *         items: The page of workshop summaries.
         *         total: Total matching workshops (before pagination).
         *         limit: Page size that was applied.
         *         offset: Offset of the first item in ``items``.
         */
        WorkshopListResponse: {
            /** Items */
            items: components["schemas"]["WorkshopResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * WorkshopResponse
         * @description Workshop summary returned by ``GET /api/workshops``.
         *
         *     Attributes:
         *         id: Workshop UUID.
         *         title: Human-readable title.
         *         starts_at: Timezone-aware start timestamp.
         *         ends_at: Timezone-aware end timestamp, or ``None``.
         *         max_capacity: Total seats.
         *         available_spots: Seats not yet reserved (max_capacity minus
         *             the count of active reservations). Computed in the
         *             service layer.
         *         registration_closes_at: Booking deadline, or ``None``
         *             (meaning "closes when the workshop starts").
         *         status: Lifecycle state (``draft`` / ``published`` /
         *             ``cancelled``).
         *         organization_id: UUID of the owning organization, or
         *             ``None`` for platform-managed workshops.
         *         created_at: Workshop creation timestamp.
         */
        WorkshopResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Max Capacity */
            max_capacity: number;
            /** Available Spots */
            available_spots: number;
            /** Registration Closes At */
            registration_closes_at?: string | null;
            /**
             * Status
             * @default published
             */
            status: string;
            /** Organization Id */
            organization_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * WorkshopReviewResponse
         * @description Review enriched with the reviewer's display name.
         *
         *     Used by the workshop detail payload so the public
         *     review list can show who wrote each review without a
         *     second round-trip per row. The reviewer's ``user_id``
         *     is retained for API consistency; the display name is
         *     joined in ``services/review_service.list_workshop_reviews``.
         *
         *     Attributes:
         *         user_name: Display name of the reviewing account.
         */
        WorkshopReviewResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workshop Id
             * Format: uuid
             */
            workshop_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Rating */
            rating: number;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User Name */
            user_name: string;
        };
        /**
         * WorkshopUpdate
         * @description Validated payload for editing a workshop (plan 1.1).
         *
         *     Every field is optional; omitted fields keep their current
         *     value. ``status`` transitions are handled by the dedicated
         *     publish/cancel endpoints rather than a free-form edit, so
         *     editing cannot accidentally un-publish a live session.
         *
         *     ``organization_id`` reassigns the workshop to another
         *     organization; the caller must be a member of the new
         *     organization (enforced in ``workshop_service.update_workshop``).
         *     Omitting it keeps the current ownership; clearing it is not
         *     supported through this payload.
         */
        WorkshopUpdate: {
            /** Title */
            title?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Max Capacity */
            max_capacity?: number | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Location */
            location?: string | null;
            /** Registration Closes At */
            registration_closes_at?: string | null;
            /** Organization Id */
            organization_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_workshops_api_workshops_get: {
        parameters: {
            query?: {
                /** @description Search term matched against title and description */
                q?: string | null;
                /** @description Exact category filter */
                category?: string | null;
                /** @description Upcoming, past, or all sessions */
                state?: string;
                limit?: number;
                offset?: number;
                /** @description Only workshops from organizations the caller follows */
                following?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workshop_api_workshops_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkshopCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_workshops_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_workshop_api_workshops__workshop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workshop_api_workshops__workshop_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkshopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workshop_api_workshops__workshop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_workshop_api_workshops__workshop_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_workshop_api_workshops__workshop_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_waitlist_api_workshops__workshop_id__waitlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistJoinResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workshop not found or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registration closed or already booked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_workshops__workshop_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workshop not found or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not ended, no past reservation, or already reviewed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rating outside the 1..5 range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    my_reservations_api_reservations_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyReservationResponse"][];
                };
            };
        };
    };
    my_waitlist_entries_api_waitlist_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyWaitlistEntryResponse"][];
                };
            };
        };
    };
    get_reservation_api_reservations__reservation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reservation not found or not owned by you */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_reservation_api_reservations__reservation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationCancelResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reservation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reservation_api_workshops__workshop_id__reservations_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied token; same value on retry replays the original reservation. */
                "Idempotency-Key": string;
            };
            path: {
                workshop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Idempotent replay of a prior successful reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workshop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workshop is full, already reserved, or registration closed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_waitlist_api_waitlist__waitlist_entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waitlist_entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntryResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Waitlist entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_api_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_organization_api_organizations__organization_id__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_organization_api_organizations__organization_id__follow_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organizer_stats_api_organizer_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerDashboardResponse"];
                };
            };
        };
    };
}
